package com.example.kaizentechnology.util

object Constants {
    const val PAGE_WIDTH = 1920
    const val HEADER_HEIGHT = 100
    const val FONT_FAMILY = "Arial"
    const val SIDE_PANEL_WIDTH = 250
    const val QUOTES_API_URL = "https://api.quotable.io/random"
    const val HOME_PAGE_INTRO = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque  penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. "
    const val PRIVACY_POLICY =
            "<p>Last updated: June 13, 2024</p>\n" +
            "<p>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>\n" +
            "<p>We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the <a style=\"color: #007CC3; text-decoration: none; \" href=\"https://www.freeprivacypolicy.com/free-privacy-policy-generator/\" target=\"_blank\">Free Privacy Policy Generator</a>.</p>\n" +
            "<h2>Interpretation and Definitions</h2>\n" +
            "<h3>Interpretation</h3>\n" +
            "<p>The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>\n" +
            "<h3>Definitions</h3>\n" +
            "<p>For the purposes of this Privacy Policy:</p>\n" +
            "<ul>\n" +
            "<li>\n" +
            "<p><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</p>\n" +
            "</li>\n" +
            "<li>\n" +
            "<p><strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where &quot;control&quot; means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</p>\n" +
            "</li>\n" +
            "<li>\n" +
            "<p><strong>Company</strong> (referred to as either &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this Agreement) refers to Kaizen Technology LLP, B-21, New York Tower, Thaltej Cross Road, Thaltej.</p>\n" +
            "</li>\n" +
            "<li>\n" +
            "<p><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</p>\n" +
            "</li>\n" +
            "<li>\n" +
            "<p><strong>Country</strong> refers to: Gujarat,  India</p>\n" +
            "</li>\n" +
            "<li>\n" +
            "<p><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</p>\n" +
            "</li>\n" +
            "<li>\n" +
            "<p><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</p>\n" +
            "</li>\n" +
            "<li>\n" +
            "<p><strong>Service</strong> refers to the Website.</p>\n" +
            "</li>\n" +
            "<li>\n" +
            "<p><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</p>\n" +
            "</li>\n" +
            "<li>\n" +
            "<p><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</p>\n" +
            "</li>\n" +
            "<li>\n" +
            "<p><strong>Website</strong> refers to Kaizen Technology, accessible from <a style=\"color: #007CC3; text-decoration: none; \" href=\"https://kaizentechnology.org.in/\" rel=\"external nofollow noopener\" target=\"_blank\">https://kaizentechnology.org.in/</a></p>\n" +
            "</li>\n" +
            "<li>\n" +
            "<p><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</p>\n" +
            "</li>\n" +
            "</ul>\n" +
            "<h2>Collecting and Using Your Personal Data</h2>\n" +
            "<h3>Types of Data Collected</h3>\n" +
            "<h4>Personal Data</h4>\n" +
            "<p>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>\n" +
            "<ul>\n" +
            "<li>\n" +
            "<p>Email address</p>\n" +
            "</li>\n" +
            "<li>\n" +
            "<p>First name and last name</p>\n" +
            "</li>\n" +
            "<li>\n" +
            "<p>Phone number</p>\n" +
            "</li>\n" +
            "<li>\n" +
            "<p>Usage Data</p>\n" +
            "</li>\n" +
            "</ul>\n" +
            "<h4>Usage Data</h4>\n" +
            "<p>Usage Data is collected automatically when using the Service.</p>\n" +
            "<p>Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>\n" +
            "<p>When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.</p>\n" +
            "<p>We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.</p>\n" +
            "<h4>Tracking Technologies and Cookies</h4>\n" +
            "<p>We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:</p>\n" +
            "<ul>\n" +
            "<li><strong>Cookies or Browser Cookies.</strong> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies.</li>\n" +
            "<li><strong>Web Beacons.</strong> Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity).</li>\n" +
            "</ul>\n" +
            "<p>Cookies can be &quot;Persistent&quot; or &quot;Session&quot; Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser. Learn more about cookies on the <a style=\"color: #007CC3; text-decoration: none; \" href=\"https://www.freeprivacypolicy.com/blog/sample-privacy-policy-template/#Use_Of_Cookies_And_Tracking\" target=\"_blank\">Free Privacy Policy website</a> article.</p>\n" +
            "<p>We use both Session and Persistent Cookies for the purposes set out below:</p>\n" +
            "<ul>\n" +
            "<li>\n" +
            "<p><strong>Necessary / Essential Cookies</strong></p>\n" +
            "<p>Type: Session Cookies</p>\n" +
            "<p>Administered by: Us</p>\n" +
            "<p>Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services.</p>\n" +
            "</li>\n" +
            "<li>\n" +
            "<p><strong>Cookies Policy / Notice Acceptance Cookies</strong></p>\n" +
            "<p>Type: Persistent Cookies</p>\n" +
            "<p>Administered by: Us</p>\n" +
            "<p>Purpose: These Cookies identify if users have accepted the use of cookies on the Website.</p>\n" +
            "</li>\n" +
            "<li>\n" +
            "<p><strong>Functionality Cookies</strong></p>\n" +
            "<p>Type: Persistent Cookies</p>\n" +
            "<p>Administered by: Us</p>\n" +
            "<p>Purpose: These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website.</p>\n" +
            "</li>\n" +
            "</ul>\n" +
            "<p>For more information about the cookies we use and your choices regarding cookies, please visit our Cookies Policy or the Cookies section of our Privacy Policy.</p>\n" +
            "<h3>Use of Your Personal Data</h3>\n" +
            "<p>The Company may use Personal Data for the following purposes:</p>\n" +
            "<ul>\n" +
            "<li>\n" +
            "<p><strong>To provide and maintain our Service</strong>, including to monitor the usage of our Service.</p>\n" +
            "</li>\n" +
            "<li>\n" +
            "<p><strong>To manage Your Account:</strong> to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.</p>\n" +
            "</li>\n" +
            "<li>\n" +
            "<p><strong>For the performance of a contract:</strong> the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.</p>\n" +
            "</li>\n" +
            "<li>\n" +
            "<p><strong>To contact You:</strong> To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.</p>\n" +
            "</li>\n" +
            "<li>\n" +
            "<p><strong>To provide You</strong> with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.</p>\n" +
            "</li>\n" +
            "<li>\n" +
            "<p><strong>To manage Your requests:</strong> To attend and manage Your requests to Us.</p>\n" +
            "</li>\n" +
            "<li>\n" +
            "<p><strong>For business transfers:</strong> We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred.</p>\n" +
            "</li>\n" +
            "<li>\n" +
            "<p><strong>For other purposes</strong>: We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.</p>\n" +
            "</li>\n" +
            "</ul>\n" +
            "<p>We may share Your personal information in the following situations:</p>\n" +
            "<ul>\n" +
            "<li><strong>With Service Providers:</strong> We may share Your personal information with Service Providers to monitor and analyze the use of our Service,  to contact You.</li>\n" +
            "<li><strong>For business transfers:</strong> We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company.</li>\n" +
            "<li><strong>With Affiliates:</strong> We may share Your information with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners or other companies that We control or that are under common control with Us.</li>\n" +
            "<li><strong>With business partners:</strong> We may share Your information with Our business partners to offer You certain products, services or promotions.</li>\n" +
            "<li><strong>With other users:</strong> when You share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside.</li>\n" +
            "<li><strong>With Your consent</strong>: We may disclose Your personal information for any other purpose with Your consent.</li>\n" +
            "</ul>\n" +
            "<h3>Retention of Your Personal Data</h3>\n" +
            "<p>The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.</p>\n" +
            "<p>The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.</p>\n" +
            "<h3>Transfer of Your Personal Data</h3>\n" +
            "<p>Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.</p>\n" +
            "<p>Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.</p>\n" +
            "<p>The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.</p>\n" +
            "<h3>Delete Your Personal Data</h3>\n" +
            "<p>You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.</p>\n" +
            "<p>Our Service may give You the ability to delete certain information about You from within the Service.</p>\n" +
            "<p>You may update, amend, or delete Your information at any time by signing in to Your Account, if you have one, and visiting the account settings section that allows you to manage Your personal information. You may also contact Us to request access to, correct, or delete any personal information that You have provided to Us.</p>\n" +
            "<p>Please note, however, that We may need to retain certain information when we have a legal obligation or lawful basis to do so.</p>\n" +
            "<h3>Disclosure of Your Personal Data</h3>\n" +
            "<h4>Business Transactions</h4>\n" +
            "<p>If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.</p>\n" +
            "<h4>Law enforcement</h4>\n" +
            "<p>Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).</p>\n" +
            "<h4>Other legal requirements</h4>\n" +
            "<p>The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:</p>\n" +
            "<ul>\n" +
            "<li>Comply with a legal obligation</li>\n" +
            "<li>Protect and defend the rights or property of the Company</li>\n" +
            "<li>Prevent or investigate possible wrongdoing in connection with the Service</li>\n" +
            "<li>Protect the personal safety of Users of the Service or the public</li>\n" +
            "<li>Protect against legal liability</li>\n" +
            "</ul>\n" +
            "<h3>Security of Your Personal Data</h3>\n" +
            "<p>The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.</p>\n" +
            "<h2>Children's Privacy</h2>\n" +
            "<p>Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.</p>\n" +
            "<p>If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent's consent before We collect and use that information.</p>\n" +
            "<h2>Links to Other Websites</h2>\n" +
            "<p>Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.</p>\n" +
            "<p>We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>\n" +
            "<h2>Changes to this Privacy Policy</h2>\n" +
            "<p>We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.</p>\n" +
            "<p>We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the &quot;Last updated&quot; date at the top of this Privacy Policy.</p>\n" +
            "<p>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>\n" +
            "<h2>Contact Us</h2>\n" +
            "<p>If you have any questions about this Privacy Policy, You can contact us:</p>\n" +
            "<ul>\n" +
            "<li>By visiting this page on our website: <a style=\"color: #007CC3; text-decoration: none; \" href=\"https://kaizentechnology.org.in/contact-us\" rel=\"external nofollow noopener\" target=\"_blank\">https://kaizentechnology.org.in/contact-us</a></li>\n" +
            "</ul>"
}

object Res {
    object Image {
        const val whiteLogo = "/white_logo.png"
        const val logo = "/kaizen_logo.png"
        const val headerImage = "/header_image.png"
        const val productBannerImage = "/product_page_banner.png"
        const val serviceBannerImage = "/services_page_banner.png"
        const val contactBannerImage = "/contact_us_banner.png"
        const val privacyPolicyBannerImage = "/privacy_policy_banner.png"
        const val contactVectorImage = "/contact_us_vector.png"
        const val aboutUsBannerImage = "/about_us_banner.png"
        const val successStoriesImage = "/success_stories.png"
        const val aboutUsIntroImage = "/about_us.png"
        const val solutionRealEstateConsultant = "/solution_real_estate_consultants.jpg"
        const val solutionPGOwner = "/solution_pg_owner.jpg"
        const val solutionPGSeeker = "/solution_pg_seeker.jpg"
        const val serviceImage = "/service_image.png"
        const val adminSupport = "/admin-support.png"
        const val lockKey = "/lock-key.png"
        const val databaseAggregator = "/database-aggregator.png"
        const val greenrooms = "/greenrooms.png"
        const val chatIcon = "/chat_icon.png"
        const val mailIcon = "/mail_icon.png"
        const val callIcon = "/call_icon.png"
        const val kaizen = "/kaizen.png"
        const val techno = "/techno.png"
        const val pig = "/pig.png"
    }
    object Icon {
        const val checkmark = "/checkmark.svg"
    }
    object Path {
        const val home = "M3 12L5 10M5 10L12 3L19 10M5 10V20C5 20.2652 5.10536 20.5196 5.29289 20.7071C5.48043 20.8946 5.73478 21 6 21H9M19 10L21 12M19 10V20C19 20.2652 18.8946 20.5196 18.7071 20.7071C18.5196 20.8946 18.2652 21 18 21H15M9 21C9.26522 21 9.51957 20.8946 9.70711 20.7071C9.89464 20.5196 10 20.2652 10 20V16C10 15.7348 10.1054 15.4804 10.2929 15.2929C10.4804 15.1054 10.7348 15 11 15H13C13.2652 15 13.5196 15.1054 13.7071 15.2929C13.8946 15.4804 14 15.7348 14 16V20C14 20.2652 14.1054 20.5196 14.2929 20.7071C14.4804 20.8946 14.7348 21 15 21M9 21H15"
        const val inquiries = "M9 5H7C6.46957 5 5.96086 5.21071 5.58579 5.58579C5.21071 5.96086 5 6.46957 5 7V19C5 19.5304 5.21071 20.0391 5.58579 20.4142C5.96086 20.7893 6.46957 21 7 21H17C17.5304 21 18.0391 20.7893 18.4142 20.4142C18.7893 20.0391 19 19.5304 19 19V7C19 6.46957 18.7893 5.96086 18.4142 5.58579C18.0391 5.21071 17.5304 5 17 5H15M9 5C9 5.53043 9.21071 6.03914 9.58579 6.41421C9.96086 6.78929 10.4696 7 11 7H13C13.5304 7 14.0391 6.78929 14.4142 6.41421C14.7893 6.03914 15 5.53043 15 5M9 5C9 4.46957 9.21071 3.96086 9.58579 3.58579C9.96086 3.21071 10.4696 3 11 3H13C13.5304 3 14.0391 3.21071 14.4142 3.58579C14.7893 3.96086 15 4.46957 15 5M12 12H15M12 16H15M9 12H9.01M9 16H9.01"
        const val logout = "M11 16.5215L7 12.5215M7 12.5215L11 8.52148M7 12.5215H21M16 16.5215V17.5215C16 18.3171 15.6839 19.0802 15.1213 19.6428C14.5587 20.2054 13.7956 20.5215 13 20.5215H6C5.20435 20.5215 4.44129 20.2054 3.87868 19.6428C3.31607 19.0802 3 18.3171 3 17.5215V7.52148C3 6.72583 3.31607 5.96277 3.87868 5.40016C4.44129 4.83755 5.20435 4.52148 6 4.52148H13C13.7956 4.52148 14.5587 4.83755 15.1213 5.40016C15.6839 5.96277 16 6.72583 16 7.52148V8.52148"
    }
}

object Id {
    const val privacyPolicyContent = "privacyPolicyContent"
    const val usernameInput = "usernameInput"
    const val passwordInput = "passwordInput"
    const val firstNameInput = "firstNameInput"
    const val lastNameInput = "lastNameInput"
    const val mobileInput = "mobileInput"
    const val emailInput = "emailInput"
    const val messageInput = "messageInput"
    const val randomQuote = "randomQuote"
    const val svgParent = "svgParent"
    const val vectorIcon = "vectorIcon"
    const val navigationText = "navigationText"
}